export const exams = [
  {
    id: 'fp3',
    name: 'FP技能士 3級',
    nameShort: 'FP3級',
    icon: '💴',
    category: 'fp',
    categoryLabel: 'FP・金融',
    tag: 'popular',
    tagLabel: '人気No.1',
    description: 'お金の教養を体系的に学ぶ入門資格。年金・保険・税金・資産運用・不動産・相続の6分野を学びます。',
    questionCount: 28,
    difficulty: '★★☆',
    examFrequency: '年3回（1月・5月・9月）',
    passRate: '約40〜50%',
    features: ['practice', 'flashcards', 'mock', 'guide', 'ai'],
  },
  {
    id: 'fp2',
    name: 'FP技能士 2級',
    nameShort: 'FP2級',
    icon: '💴',
    category: 'fp',
    categoryLabel: 'FP・金融',
    tag: 'popular',
    tagLabel: '実務向け',
    description: '実務に直結する中級資格。AFP認定と同時取得も可能。FP3級取得後のステップアップに最適。',
    questionCount: 90,
    difficulty: '★★★',
    examFrequency: '年3回（1月・5月・9月）',
    passRate: '約30〜40%',
    features: ['practice', 'flashcards', 'mock', 'guide', 'ai'],
  },
  {
    id: 'boki3',
    name: '日商簿記 3級',
    nameShort: '簿記3級',
    icon: '📊',
    category: 'accounting',
    categoryLabel: '会計・経理',
    tag: 'popular',
    tagLabel: '就職に有利',
    description: 'ビジネスの共通言語を学ぶ。資金の流れを正しく把握し、仕訳・決算の基礎知識を身につけます。',
    questionCount: 10,
    difficulty: '★★☆',
    examFrequency: '年3回（6月・11月・2月）',
    passRate: '約40〜50%',
    features: ['practice', 'flashcards', 'guide', 'ai'],
  },
  {
    id: 'boki2',
    name: '日商簿記 2級',
    nameShort: '簿記2級',
    icon: '📊',
    category: 'accounting',
    categoryLabel: '会計・経理',
    tag: 'soon',
    tagLabel: '近日追加',
    description: '商業簿記・工業簿記を習得。経理・会計職への転職や昇進に大きく有利な資格。',
    questionCount: 0,
    difficulty: '★★★',
    examFrequency: '年3回（6月・11月・2月）',
    passRate: '約20〜30%',
    features: ['practice', 'flashcards', 'guide', 'ai'],
  },
  {
    id: 'takken',
    name: '宅地建物取引士',
    nameShort: '宅建士',
    icon: '🏠',
    category: 'realestate',
    categoryLabel: '不動産',
    tag: 'soon',
    tagLabel: '近日追加',
    description: '不動産取引の国家資格。不動産業界では必須の資格で、独占業務があります。',
    questionCount: 0,
    difficulty: '★★★',
    examFrequency: '年1回（10月）',
    passRate: '約15〜17%',
    features: ['practice', 'flashcards', 'mock', 'guide', 'ai'],
  },
  {
    id: 'it_passport',
    name: 'ITパスポート',
    nameShort: 'ITパスポート',
    icon: '💻',
    category: 'it',
    categoryLabel: 'IT・テクノロジー',
    tag: 'soon',
    tagLabel: '近日追加',
    description: 'ITの基礎知識を証明する国家資格。文系・理系問わず社会人・学生に人気の資格。',
    questionCount: 0,
    difficulty: '★★☆',
    examFrequency: '随時（CBT方式）',
    passRate: '約50〜55%',
    features: ['practice', 'flashcards', 'mock', 'guide', 'ai'],
  },
]

export const featureLabels = {
  practice: { label: '練習問題', icon: '📝' },
  flashcards: { label: '知識カード', icon: '🃏' },
  mock: { label: '模擬試験', icon: '📋' },
  guide: { label: '学習ガイド', icon: '📖' },
  ai: { label: 'AI解説', icon: '🤖' },
}
